{% set name = "protobuf3-to-dict" %}
{% set version = "0.1.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 1e42c25b5afb5868e3a9b1962811077e492c17557f9c66f0fe40d821375d2b5a

build:
  number: 9
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - protobuf >=2.3.0
    - python
    - six

test:
  imports:
    - protobuf_to_dict
  requires:
    - coverage
    - nose >=1.0
    - nosexcover

about:
  home: "https://github.com/kaporzhu/protobuf-to-dict"
  license: Unlicense 
  license_file: LICENSE
  summary: "Ben Hodgson: A teeny Python library for creating Python dicts from protocol buffers and the reverse."
  dev_url: "https://github.com/kaporzhu/protobuf-to-dict"

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - benhuff
    - oblute
